# Generated by Django 5.1.4 on 2025-03-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="make",
            new_name="brand",
        ),
    ]
