# Generated by Django 5.1.4 on 2025-03-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0002_rename_make_vehicle_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailylog",
            name="stop_location",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
