# Generated by Django 5.1.4 on 2025-03-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0003_dailylog_stop_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
