# Generated by Django 5.1.4 on 2025-03-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0004_trip_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="date",
            field=models.DateField(),
        ),
    ]
